server:
  port: 8090

spring:
  application:
    name: spring-boot-with-docker

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true